name: build new image and deploy on Render
run-name: Render deployment
on: push
jobs:
  build-and-publish-project:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v6.0.2
      - name: dotnet setup
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: get dependencies
        run: dotnet restore
      - name: build project
        run: dotnet build --no-restore
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v4.0.0
      - name: log in to Docker Hub
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push Docker image
        uses: docker/build-push-action@v7.1.0
        with:
          context: ./express-app/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dn-project:auto
      - name: deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
